// user_front/components/footer.vue
<template>
  <div class="footer">
    ︎©︎長岡技術科学大学技大祭実行員
  </div>
</template>

<style>
  .footer{
    font-family: Noto Sans JP;
    @apply
    flex
    justify-center
    items-center
    absolute
    inset-x-0
    bottom-0
    border-t-2
    mx-4
    text-xs
    h-[35px]
    font-light
    leading-4
    fixed;
  }
</style>

// user/src/components/Footer/Footer.tsx
import { FC } from "react";

const Footer: FC = () => {
  const currentYear = new Date().getFullYear();

  return (
    <footer className="fixed bottom-0 left-0 w-full h-20 bg-green-600 flex justify-center items-center px-8 text-xs font-light text-white">
      Copyright © {currentYear} NUTMEG. All Rights Reserved.
    </footer>
  );
};

export default Footer;
