// user_front/components/Modal.vue
<script setup lang="ts">
interface Order {
  title: string
}
const props = withDefaults(defineProps<Order>(), {
	title: '',
})
</script>

<template>
	<div class="fixed top-0 left-0 h-full w-full	p-24 z-10 bg-[#333]/30 overflow-auto" >
		<div class="flex p-4 mx-[30%] justify-center bg-[#dadada] rounded-lg flex-col">
			<slot name="close"/>
			<div class="text-3xl font-medium text-center">{{ props.title }}</div>
			<slot name="form"></slot>
		</div>
	</div>
</template>

// admin/src/components/Modal/Modal.tsx
import { FC, ReactNode, useEffect } from 'react';

export type ModalProps = {
  isOpen: boolean;
  onClose: () => void;
  title?: string;
  children: ReactNode;
  className?: string;
};

const Modal: FC<ModalProps> = ({
  isOpen,
  onClose,
  title,
  children,
  className = '',
}) => {
  useEffect(() => {
    if (isOpen) {
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = 'unset';
    }
    return () => {
      document.body.style.overflow = 'unset';
    };
  }, [isOpen]);

  if (!isOpen) return null;

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/50"
      onClick={onClose}
    >
      <div
        className={`max-h-[90vh] w-full max-w-2xl overflow-auto rounded-lg bg-white p-8 shadow-xl ${className}`}
        onClick={(e) => e.stopPropagation()}
      >
        {title && <h2 className="mb-6 text-2xl font-bold">{title}</h2>}
        <div className="modal-content">{children}</div>
      </div>
    </div>
  );
};

export default Modal;
